In [21]:
# import numpy library
import numpy as np

# create a one dimensional vector
x = np.array([1,2,3,4])
x

# create a (3x2) matrix
A = np.array([[1,2],[3,4],[5,6]])
A

# See the type of x and A
print('type x:', type(x))
print('type A:', type(A))

# See the shape of x and A
print('Shape x:', x.shape)
print('Length x:', len(x))
print('Shape A:', A.shape)

# Transpose A using two dimilar methods
A_T = A.T
print(A_T)
print('Shape A_T:', A_T.shape)

A_T = A.transpose()
A_T

# Create matrix B
B = np.array([[2,5],[7,4],[4,3]])
print(B, '= B')

C = A + B
print(C, '= A + B = C')

D = A + 1
print(D, '= A + 1 = D')


type x: <class 'numpy.ndarray'>
type A: <class 'numpy.ndarray'>
Shape x: (4,)
Length x: 4
Shape A: (3, 2)
[[1 3 5]
 [2 4 6]]
Shape A_T: (2, 3)
[[2 5]
 [7 4]
 [4 3]] = B
[[ 3  7]
 [10  8]
 [ 9  9]] = A + B = C
[[2 3]
 [4 5]
 [6 7]] = A + 1 = D


In [26]:
# Matrix Multiplication - .dot() fuction
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2],[4]])
A,B

C = np.dot(A, B)
C

C = A.dot(B)

C.shape

(3, 1)

In [30]:
# Identity Matrix
I = np.eye(3)
I

IA = I.dot(A)
A, IA

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1., 2.],
        [3., 4.],
        [5., 6.]]))

In [33]:
# Determinant
M = np.array([[1,2],[3,4]])
M

det_M = np.linalg.det(M)
det_M

# Error for non-square array
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)

LinAlgError: Last 2 dimensions of the array must be square

In [38]:
# Inverse Matrices
A = np.array([[3,0,2],[2,0,-2],[0,1,1]])
A

A_inv = np.linalg.inv(A)
A, A_inv

I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])