# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [27]:
a = np.random.randint(1,50,(1,9))
print(a)

[[44 38 43 26 35 25  3  7 39]]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [28]:
np.flip(a)


array([[39,  7,  3, 25, 35, 26, 43, 38, 44]])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
b = np.random.randint(0,9,(3,3))
print(b)

[[8 5 4]
 [5 8 0]
 [1 1 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [38]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [39]:
c = np.random.randint(0,9,(3,3,3))
print(c)

[[[0 4 6]
  [5 2 0]
  [2 0 8]]

 [[2 6 6]
  [6 6 5]
  [2 1 4]]

 [[0 0 6]
  [8 3 0]
  [4 0 7]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [50]:
d = np.random.rand(10,10)
print(d)
print(np.min(d))
print(np.max(d))

[[0.96187151 0.97962483 0.56298268 0.03365727 0.56197441 0.40080897
  0.70995045 0.53774416 0.48588774 0.19530443]
 [0.95191052 0.47820998 0.79999676 0.6210836  0.62008487 0.94009162
  0.7352043  0.24619423 0.96850869 0.19018586]
 [0.77952891 0.36139473 0.70590565 0.9863492  0.16452346 0.80546504
  0.96283336 0.13705512 0.19213185 0.10743403]
 [0.62464348 0.68402316 0.28597635 0.85634725 0.88910252 0.84108196
  0.53722822 0.50142446 0.24524044 0.12540214]
 [0.06512348 0.61170122 0.14861504 0.78847219 0.96171248 0.67270489
  0.37435031 0.06613501 0.72554047 0.7840438 ]
 [0.72996797 0.43923877 0.19356231 0.847133   0.9458029  0.5558041
  0.72528003 0.11434661 0.11186782 0.17215316]
 [0.08333876 0.96323268 0.72394781 0.07602287 0.84414808 0.01538183
  0.21718975 0.44199971 0.30387906 0.40491714]
 [0.08677797 0.39638852 0.54723173 0.16497695 0.05128628 0.19522006
  0.36452025 0.68774442 0.48260838 0.88961851]
 [0.26652244 0.84912404 0.90424251 0.89670236 0.34195767 0.54368655
  0.58586518 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
e = np.random.rand(30)
print(e)
np.mean(e)

[0.60235114 0.98908151 0.57980835 0.86923703 0.74454167 0.47671725
 0.62525453 0.40346621 0.57866067 0.48369881 0.53600478 0.73509325
 0.19341375 0.7209874  0.25259909 0.32294183 0.83418831 0.43816912
 0.13729422 0.10892662 0.13926878 0.55005888 0.26949768 0.68684319
 0.95446777 0.5051429  0.06830719 0.70897391 0.92004168 0.9256907 ]


0.5453576071575849

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [63]:
a = np.ones([7,7])
b = np.zeros([5,5])
a[1:6,1:6] = b
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [81]:
b = np.random.randint(0,9,(3,3))
print(b)
r,c = b.shape
d = np.zeros((r+2,c+2))
d[1:(r+1),1:(c+1)] =b
print(d)

[[7 2 8]
 [6 4 2]
 [1 3 7]]
[[0. 0. 0. 0. 0.]
 [0. 7. 2. 8. 0.]
 [0. 6. 4. 2. 0.]
 [0. 1. 3. 7. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [90]:
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [96]:
a = np.zeros([5,5])
b = np.array([1,2,3,4])
a[[1,2,3,4],[0,1,2,3]] = b
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [102]:
g = np.zeros((6,7,8))
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [124]:
b = np.random.randint(0,5,(5,5))
print(b)
norm = np.linalg.norm(b)
det = np.linalg.det(b)
print(b/norm)

[[3 1 2 0 0]
 [3 1 2 3 0]
 [2 4 4 0 3]
 [2 0 0 0 0]
 [1 4 4 2 2]]
[[0.26620695 0.08873565 0.1774713  0.         0.        ]
 [0.26620695 0.08873565 0.1774713  0.26620695 0.        ]
 [0.1774713  0.3549426  0.3549426  0.         0.26620695]
 [0.1774713  0.         0.         0.         0.        ]
 [0.08873565 0.3549426  0.3549426  0.1774713  0.1774713 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [164]:
a = np.random.randint(0,11,(1,9))
print(a)

with np.nditer(a, op_flags=['readwrite']) as it:
    for i in it:
        if 3<i<8:
            i[...] = i*(-1)

print(a)

[[3 4 4 0 8 5 0 9 4]]
[[ 3 -4 -4  0  8 -5  0  9 -4]]


#### 29. How to round away from zero a float array ? (★☆☆)

In [168]:
d = np.random.rand(3,3) * 8
print(d)
np.ceil(d)

[[0.17245985 2.68384322 6.44486996]
 [6.49696302 5.64775865 2.36875124]
 [6.96286319 7.26074911 0.64883828]]


array([[1., 3., 7.],
       [7., 6., 3.],
       [7., 8., 1.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [170]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,22,3,4],[5,56,73,8]])

np.intersect1d(a,b)

array([1, 3, 4, 5, 8])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [178]:
def gen_func():    
    for i in range(10):
        yield i
    
d = np.fromiter(gen_func(), int)

print(d)   


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [181]:
d = np.linspace( 2, 11, 10)
print(d)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [188]:
a = np.random.randint(0,11,(1,10))
print(a)

#np.sort(a)
a.sort()
print(a)

[[ 0  8  6  5  5 10  8  9  5  0]]
[[ 0  0  5  5  5  6  8  8  9 10]]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [196]:
print(np.array_equal(a,b))
np.allclose(a,d, 10)

False


True

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [231]:
a = np.random.random(10)
print(a)
print(np.argmax(a))
a[np.argmax(a)]=0
a

[0.01181939 0.17575361 0.83781867 0.9082183  0.56402315 0.55268008
 0.09529371 0.56141872 0.4040501  0.70626942]
3


array([0.01181939, 0.17575361, 0.83781867, 0.        , 0.56402315,
       0.55268008, 0.09529371, 0.56141872, 0.4040501 , 0.70626942])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [282]:
a = np.random.randint(0,100, size = (1,50))
print(a)
scalar = 42
i = np.argmin(np.absolute(a-scalar))
print(i, a[0,i])

[[39 77 97  4 75 92 43  4 40 15 55 74 81 61 33 11 69 15 75 75 38 41  9 74
   4 46 31 98 41 58 44 58 99 99  1 11 28  9 13 72 29 66 22 69 37 90 18 87
  14 52]]
6 43


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [291]:
a = np.array([1,2,3],dtype = 'float32')
print(a)
a = a.astype('int32', copy = False)
print(a)

[1. 2. 3.]
[1 2 3]


#### 59. How to sort an array by the nth column? (★★☆)

In [295]:
b = np.random.randint(0,10,(3,3))
print(b)

print(b[np.argsort(b[:1])])

[[2 5 4]
 [3 0 0]
 [2 4 0]]
[[[2 5 4]
  [2 4 0]
  [3 0 0]]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [342]:
b = np.random.randint(0,3,(3,8))
print(b)
# create an array showing which columns are null
c = (~b.any(axis = 0))
print(c)
# return True if any column is null
d = (~b.any(axis = 0).all())
print(d)

[[1 2 0 0 0 1 0 0]
 [2 1 1 1 1 1 0 2]
 [1 2 0 0 0 2 0 2]]
[False False False False False False  True False]
True


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [380]:
a = np.array([1,2,3,4,5])
w = (len(a)-1)
zeros = 3
b = np.zeros((1,(w)*zeros))
for i in a:
    i-=1
    b = np.insert(b,(w*i),a[i])
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [436]:
b = np.random.randint(0,3,(3,8))
print(b)

b[[0,1]] = b[[1,0]]
print(b)

[[0 0 0 1 0 0 1 0]
 [1 2 2 1 0 1 1 2]
 [0 2 2 1 1 1 1 2]]
[[1 2 2 1 0 1 1 2]
 [0 0 0 1 0 0 1 0]
 [0 2 2 1 1 1 1 2]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [433]:
b = np.random.randint(0,3,(3,8))
print(b)

np.logical_not(b)
np.negative(b)

[[1 1 1 1 2 0 1 1]
 [0 0 2 0 0 1 2 1]
 [1 0 1 0 2 1 0 2]]


array([[-1, -1, -1, -1, -2,  0, -1, -1],
       [ 0,  0, -2,  0,  0, -1, -2, -1],
       [-1,  0, -1,  0, -2, -1,  0, -2]])

#### 83. How to find the most frequent value in an array?

In [458]:
b = np.random.randint(0,10,50)
print(b,"\n")

print(np.arange(0,10))
print(np.bincount(b),'\n')

print(np.bincount(b).argmax())


[8 6 8 3 2 7 7 4 4 6 4 9 8 5 3 7 6 7 3 4 2 8 9 1 7 1 3 1 4 3 9 1 8 2 5 5 4
 6 7 3 7 3 5 5 8 4 0 3 6 8] 

[0 1 2 3 4 5 6 7 8 9]
[1 4 3 8 7 5 5 7 7 3] 

3


#### 89. How to get the n largest values of an array (★★★)

In [476]:
n = 5
b = np.random.randint(0,10,50)
print(b,"\n")

w = np.argmax(b)
print(b[w], w)

print (b[np.argsort(b)[-n:]])

[6 0 3 9 9 9 9 6 8 8 0 1 1 9 1 3 8 2 4 2 0 8 5 7 7 4 1 4 7 6 0 0 8 2 0 8 4
 3 8 0 2 8 8 4 3 0 4 7 5 4] 

9 3
[9 9 9 9 9]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [485]:
b = np.random.randint(0,2,(8,2))
print(b)

a,c = np.unique(b, axis = 0, return_counts = True)
print(a,c)
print(a[c==1])

[[1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 1]
 [1 1]] [1 1 6]
[[0 0]
 [0 1]]
