In [2]:
import numpy as np

#### The Basics

In [21]:
a = np.array([1,2,3],dtype = 'int32')
print(a)

[1 2 3]


In [183]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
b.ndim

2

In [10]:
# Get Shape - rows by columns
b.shape

(2, 3)

In [15]:
# Get type
b.dtype

dtype('float64')

In [17]:
# Get Size
b.itemsize

8

In [22]:
# Get total Size
a.size * a.itemsize

12

In [23]:
# Get total size
a.nbytes

12

**Accessing/Changing specific elements, rows, columns, etc**

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get a sprcific element [r,c]
a[1,-2] == a[1,5] == 13

True

In [29]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [31]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [33]:
# Change element
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# Get specific element (work outside in)

b[:,1,1]

array([4, 8])

In [40]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### **Initializing Different Types of Arrays**

In [44]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [47]:
# Any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [50]:
# any other number (full_like)
np.full_like(a, 4) == np.full(a.shape,4)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [53]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.11107552, 0.68431692],
       [0.86304385, 0.15122667],
       [0.11970592, 0.7882875 ],
       [0.45087158, 0.08897989]])

In [80]:
# Random integer values
np.random.randint(1,7, size=(3,3))

array([[5, 3, 5],
       [3, 5, 3],
       [1, 6, 2]])

In [81]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [100]:
x = np.ones((5,5))
print(x)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

x[1:-1,1:-1] = z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be Careful when copying arrays!!!

a = np.array([1,2,3])

b = a.copy()
print(a,b)

b[0] = 100
print(a,b)


#### Mathematics

In [127]:
a = np.array([1,2,3,4])

In [115]:
a + 2

array([3, 4, 5, 6])

In [126]:
#a += 2
a

array([13, 14, 15, 16])

In [119]:
a - 2

array([-1,  0,  1,  2])

In [117]:
a * 2

array([2, 4, 6, 8])

In [120]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [128]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [129]:
a ** 2

array([ 1,  4,  9, 16])

In [130]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [138]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)
print(a.dot(b))
print(b.dot(a))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [140]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [142]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
np.min(stats, axis = 1)

array([1, 4])

In [148]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [149]:
np.sum(stats)

21

##### Reorganizing Arrays

In [156]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, before.shape)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [160]:
# Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Miscellaneous

In [165]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [180]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [174]:
np.any(filedata > 50, axis = 0)
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [179]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [169]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])